import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import HowTo from "../components/HowTo";
import Navbar from "../components/Navbar";
import Storage from "../components/Storage";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className='bg-background text-white'>
                <Navbar />
                <Hero />
                <About />
                <Storage />
                <HowTo />
            </main>

            <Footer />
        </div>
    );
};

export default Home;
